name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests_unit:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.3', '7.4', '8.0']
        phpunit-versions: ['latest']
        include:
            - php-versions: '5.6'
              phpunit-versions: '5.x'
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with: 
        php-version: ${{ matrix.php-versions }}
        tools: phpunit:${{ matrix.phpunit-versions }}
    
    - name: php version
      run: php -v

    - name: phpunit version
      run: phpunit -v

    - name: Run test suite
      run: phpunit --bootstrap tests/config.php tests
