name: PHP Composer

on:
  push:
    branches: 
      - test-tag
    tags:
      - "*"
  pull_request:
    branches: 
      - test-tag

jobs:
  tests_unit:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.3', '7.4', '8.0']
        phpunit-versions: ['8.5.15']
        include:
        - php-versions: '5.6'
          phpunit-versions: '5.7.27'
        - php-versions: '7.0'
          phpunit-versions: '6.5.14'
    
    name: Php Version ${{matrix.php-versions }} / php Unit ${{ matrix.phpunit-versions }}
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with: 
        php-version: ${{ matrix.php-versions }}
        tools: phpunit:${{ matrix.phpunit-versions }}
    
    - name: php version
      run: php -v

    - name: Run test suite
      run: phpunit --bootstrap tests/config.php tests --configuration tests/phpunit.xml

  update_lib_version:
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@master
        - name: Get the version
          run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        - name: Test
          run: |
            echo  $RELEASE_VERSION
            sed -i 's/"LIBRARY_VERSION": "*.*"/"version": "${{ env.RELEASE_VERSION }}"/' Config.php
            git config --global user.email "ilajili@payplug.com"
            git config --global user.name "ilajili"
            git remote set-url origin https://github.com/payplug/payplug-php
            git add .
            git commit -m "update version"
            git push origin HEAD:test-tag
