name: Release

on:
  push:
    tags:
      - "*"
  workflow_run:
    workflows: [ "PHP Composer" ]
    types:
      - completed
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: test echo
      run: echo ${{ github.event.workflow_run.conclusion }}

  on-success:

    runs-on: ubuntu-18.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN}}
      - name: Fetch library version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Apply new version from tag
        run: |
          echo  $RELEASE_VERSION
          sed -i "s/LIBRARY_VERSION = '*'/LIBRARY_VERSION = '${{ env.RELEASE_VERSION }}'/" lib/Payplug/Core/Config.php
          git config user.email actions@github.com
          git config user.name "GitHub Actions"
          git add .
          git commit -m "[Automated Release Action]"
          git push origin HEAD:test-tag

  on-failure:

      runs-on: ubuntu-18.04
      if: ${{ github.event.workflow_run.conclusion == 'failure' }}
      steps:
        - run: echo 'Unit tests previously failed, abording release !'